### ISSUE TITLE
Limelight documentation

### ISSUE THREAD

**Issue by slownie** [frc5024/webdocs#15]
We need documentation on limelight. Do it well.

**Comment by Ewpratten** [comment]
This should include:
 - How to physically connect and use a Limelight with the robot
 - How to use it in our code 
 - Basics of using the web tool
 - A link to the official docs for more info

Remember to mention that the address is http://10.50.24.11:5801

**Comment by Ewpratten** [comment]
@slownie Do you want to assign more people?

**Comment by Ewpratten** [comment]
Just took a look at your work. Looking good!

**Comment by Ewpratten** [comment]
This has been largely done by #25 But there are still a few small changes to make to the page. I will create issues for each
