### ISSUE TITLE
Add document for "Cheesy drive"

### ISSUE THREAD

**Issue by Ewpratten** [frc5024/webdocs#7]
@hyperliskdev has been playing with [Cheesy drive](https://github.com/Team254/FRC-2019-Public/blob/f99f09a15a2c8e7b5df868ec3a4a81105dc88112/src/main/java/com/team254/frc2019/subsystems/Drive.java#L278-L301) / [Curvature drive](https://github.com/wpilibsuite/allwpilib/blob/4f034e6c142c9906b7852fe10592923ee58659d6/wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java#L247-L314), and I think this should get it's own how-to page in the *"Learning"* section. 

This page should include:
 - Why and when cheesy drive should be used
 - It's history (hint: it was developed by 254)
 - How to use it in one of our robot programs
 - How it works

**Comment by Ewpratten** [comment]
For information on how to update a webdocs page, see [the guide](https://cs.5024.ca/webdocs/docs/meta). Don't forget to add your GitHub username to the page's authors list!

**Comment by Ewpratten** [comment]
This **MUST** be finished by Friday DEC6 @hyperliskdev

**Comment by hyperliskdev** [comment]
I apologize, it'll be finished and pushed tonight.

**Comment by Ewpratten** [comment]
published
